---
- name: Open Minecraft port in UFW
  hosts: client2
  become: true
  tasks:
    - name: Allow Minecraft port through UFW
      SUDO UFW: 
        rule: allow
        port: 25565
        proto: tcp

