---
- name: Open Minecraft port in UFW
  hosts: client2
  become: yes
  tasks:
    - name: Allow Minecraft port through UFW
      ufw: 
        rule: allow
        port: 25565
        proto: tcp

